// operations
const OP_START = 'START';
const OP_COMMAND = 'COMMAND';
const OP_CHANNEL_STATUS = 'CHANNEL_STATUS';
const OP_PROGRESS = 'PROGRESS';
const OP_STATUS = 'STATUS';
const OP_NONE = 'NONE';
const OP_END = 'END';

// actions
const ACTION_DIAL = 'dial';
const ACTION_TWIML = 'twiml';
const ACTION_ATTACH = 'attach';
const ACTION_RELEASE = 'release';

// test status
const TEST_STATUS_PENDING = 'PENDING';
const TEST_STATUS_READY = 'READY';
const TEST_STATUS_STARTED = 'STARTED';
const TEST_STATUS_ENDED = 'ENDED';

// command status
const CMD_STATUS_STARTED = 'STARTED';
const CMD_STATUS_ENDED = 'ENDED';

// step status
const STEP_STATUS_READY = 'READY';
const STEP_STATUS_STARTED = 'STARTED';
const STEP_STATUS_ENDED = 'ENDED';

// party status
const PARTY_STATUS_PENDING = 'PENDING';
const PARTY_STATUS_STARTED = 'STARTED';
const PARTY_STATUS_ENDED = 'ENDED';

module.exports = {
  OP_START,
  OP_COMMAND,
  OP_CHANNEL_STATUS,
  OP_PROGRESS,
  OP_STATUS,
  OP_NONE,
  OP_END,
  ACTION_ATTACH,
  ACTION_DIAL,
  ACTION_TWIML,
  ACTION_RELEASE,
  TEST_STATUS_PENDING,
  TEST_STATUS_READY,
  TEST_STATUS_STARTED,
  TEST_STATUS_ENDED,
  CMD_STATUS_STARTED,
  CMD_STATUS_ENDED,
  STEP_STATUS_READY,
  STEP_STATUS_STARTED,
  STEP_STATUS_ENDED,
  PARTY_STATUS_PENDING,
  PARTY_STATUS_STARTED,
  PARTY_STATUS_ENDED
};
