// state changes
const CHG_CHANNEL_STATUS = 'CHANNEL_STATUS';
const CHG_CLIENT_READY = 'CLIENT_READY';
const CHG_END_COMMAND = 'END_COMMAND';
const CHG_END_PARTY = 'END_PARTY';
const CHG_END_TEST = 'END_TEST';
const CHG_START_TEST = 'START_TEST';
const CHG_STATS = 'CHG_STATS';

// operations
const OP_START = 'START';
const OP_COMMAND = 'COMMAND';
const OP_CHANNEL_STATUS = 'CHANNEL_STATUS';
const OP_PROGRESS = 'PROGRESS';
const OP_STATUS = 'STATUS';
const OP_STATS = 'STATS';
const OP_NONE = 'NONE';
const OP_END = 'END';

// test status
const TEST_STATUS_PENDING = 'PENDING';
const TEST_STATUS_READY = 'READY';
const TEST_STATUS_STARTED = 'STARTED';
const TEST_STATUS_ENDED = 'ENDED';

// party status
const PARTY_STATUS_PENDING = 'PENDING';
const PARTY_STATUS_STARTED = 'STARTED';
const PARTY_STATUS_ENDED = 'ENDED';

module.exports = {
  CHG_CHANNEL_STATUS,
  CHG_CLIENT_READY,
  CHG_END_COMMAND,
  CHG_END_PARTY,
  CHG_END_TEST,
  CHG_START_TEST,
  CHG_STATS,
  OP_START,
  OP_COMMAND,
  OP_CHANNEL_STATUS,
  OP_PROGRESS,
  OP_STATS,
  OP_STATUS,
  OP_NONE,
  OP_END,
  TEST_STATUS_PENDING,
  TEST_STATUS_READY,
  TEST_STATUS_STARTED,
  TEST_STATUS_ENDED,
  PARTY_STATUS_PENDING,
  PARTY_STATUS_STARTED,
  PARTY_STATUS_ENDED
};
